Sirajmolla/Hacktoberfest-2022

Calculator.c
Name : Awaneesh Soni
Institute : IIT BHU
=> Added Calculator.c file

Kth Largest Element in an Array.cpp
Given an integer array nums and an integer k, return the kth largest element in the array.
Note that it is the kth largest element in the sorted order, not the kth distinct element.
=> Kth Largest Element in an Array

three-sum.cpp
Hey !!
Three sum problem is one of the very common questions asked in interviews nowadays. I think this contribution would add another good question to your repository.
I am a participant in Hacktober Fest 2022. 
Thank you in advance.
=> Two Pointers array problem in C++

bigm.cpp
Big M method is used to solve linear equations and is an advancement over the simplex method.
=> Added Big M algorithm

Subarray with given sum.cpp
Subarray with given sum 
Given an unsorted array A of size N that contains only non-negative integers, find a continuous sub-array which adds to a given number S.
In case of multiple subarrays, return the subarray which comes first on moving from left to right.
Example 1:
Input:
N = 5, S = 12
A[] = {1,2,3,7,5}
Output: 2 4
Explanation: The sum of elements 
from 2nd position to 4th position 
is 12.
=> Added subarray with given sum in c++

buyAndSell.js
Wrote an algorithm to solve Best Time to Buy and Sell Stock using javascript
=> added program for Best Time to Buy and Sell Stock

HeapSort
please merge my pull request into your repository.
=> Heap sort-hacktoberfest-2022

Stack_Sort.cpp
=> Create Stack Sort Program

instra_bot.py
This script can automate our instragram and can perform different task on feed like
>commenting on someone picture 
>getting all followers of account etc.
=> Instragram Bot

PalindromeWord.java
I have added a java program that checks whether a word is palindrome(a word where the original word and its reversed form are the same) or not.
=> Added java program to check whether a word is palindrome or not

Birthday_reminder.py
It's a birthday reminder made using python. Please check and merge the pull request.
=> Birthday_reminder

code to FIND any ELEMENT INDEX using LINEAR SEARCH.CPP
PLEASE ACCEPT MY PULL REQUEST.
AND ALSO PLEASE GIVE HACTOBERFEST LABLE.
THANK YOU.
=> Create code to FIND any ELEMENT INDEX using LINEAR SEARCH.CPP

Karatsuba_algo.cpp
This pull request contains Karatsuba Algorithm for fast multiplication
=> Added karatsuba algorithm for fast multiplication

reverse string using stack.cpp
algorithm for reversing the string using stack
please add this algo in your repository 
hope you find it useful.
=> reverse string using stack

ListMap.scala
please add this as it tells about basic operation os list map in scala language
=> create basic operations  listmap.scala

sum_of_two_array.cpp
=> Sum of two arrays

TicTacToeGame/index.html, TicTacToeGame/script.js, TicTacToeGame/style.css
hi please accept ad merge my pr. thanks
=> add tictactoegame

Python/turtle race.py
turtle race game using turtle library python
please accept the changes
=> turtle race game

C++/Binary_tree.cpp
Binary tree one driver program having functionality:-
->insertion
->traversel
->check bst or not
-> find the height of tree
->searching in bst
=> Binary_tree.cpp

Pascal'sTriangle.java
I have created Pascal's Triangle using java.
In Pascal's Triangle, each new number lies between two numbers and below them, and its value is the sum of the two numbers above it.
Please accept my PR :)
=> Create Pascal's Triangle using Java

python/fakenewsdetection.py
using python and streamlit library
=> detects fake news

Python/fibonaccifunction.py, contributors.md
This is a python program to find the fibonacci series for a given nth  number
Have also updated the contributors.md and have added my name as instructed.
=> Write a program to print the Fibonacci series up to a given number

Python/BubbleSort.py
Hi, I have added code to Bubble sort using Python. Please accept my Pull request. TIA
=> Add Bubble Sort

C++/Merge K Sorted Lists.cpp
Kindly merge the pr under hacktoberfest submissions.
Thank you in advance!!
=> Added Merge K sorted list c++

Python/devto_posts_backup.py
Kindly merge the pr under hacktoberfest submissions.
Thank you in advance!!
=> add Devto Posts scraper via public API

C++/constructors_destructors.cpp, C++/function_overloading.cpp, C++/hierarchical_inheritance.cpp, C++/static_datamember_functions.cpp
Please add my code to your repository with hacktoberfest label
=> hierarchical_inheritance

Bubble sort.txt, mergesort.txt, quicksort.txt
please add my file to your repository with the label hactoberfest.
=> Added to mergesort

C/LinkedListInsertionAtSpecificPosition.c
C program of singly linked list to perform insertion at any specific location. 😃
=> Created C program of Singly linked list.

C/double_triangle.c, C/guessing_the_number.c, C/square.c
Thanks for reading my pull request
=> Create C codes

Java/armstrong.java
please add my file to your repository with label as hacktoberfest
=> hacktoberfest-2022

Python/MinMaxNorm.py
Min-max normalization (usually called feature scaling) performs a linear transformation on the original data. This technique gets all the scaled data in the range (0, 1).
=> added min-max norm method

fire-detection/main.py
Added a new project fire detection in python
=> adding fire detection project in python

coffeewindingmachine.py
Greetings!
I would you request you to accept my PR and merge it! I have added up the code for Coffee Winding Machines used in Cafes!
=> Coffee Winding Machine Python Program

C++/phone_keyboard.cpp
please merge this pull request .
=> Added code of letter combination of phone number in cpp language 

Java/Checl_Prime.java
Thank you for reading this pull request.
=> Check prime number or not

Python/Twitter-RT-bot/README.md, Python/Twitter-RT-bot/twitter-bot.py
**Pull request Twitter-Retweet-Bot**
=> Twitter-Retweet-bot

C/Array_traversal.c
Please review my code and merge it under hactoberfest accepted.
=> Added a C program of array traversal.

Java/Binary_Search.java
Could you please accept this contribution?
I am a HacktoberFest participant and this would really help.
=> Added Binary Search in Java

python/Merge Sort.py
A python program to implement Merge Sort in Python
=> Merge Sort

Java/stack.java
JAVA stack - push() ,  pop() ,  peek () ;
=> JAVA stack - push() ,  pop() ,  peek () ;

C++/Binary_substitution.cpp, C++/Book_Allocation.cpp, C++/Building a heap using cpp, C++/C++ Program to Reverse an Integer, C++/EnvelopePattern.cpp, C++/FindPeakElementA.cpp, C++/Merge Two Sorted Lists.cpp, C++/Permutations in C++.cpp, C++/ReverseNo.cpp, C++/Trapping Rain Water.c++, C++/binary_search.cpp, C++/longest_common_subsequence_dp.cpp, C++/richest-customer-wealth.cpp, C++/vertical_order_bt.cpp
=> Added Some C++ Programs

Python/Tutorial/remove_pairs.py
=> Removedor de números pares

Python/img2jpeg.py
=> Created img2jpeg

Java/RainWater.java, Python/BubbleSort.py
=> Add new problem 

python/Factorial.py
=> Modified Python/Factorial.py

Java/swap_swings.java
Swings Java GUI-Based Swap Two Numbers Program
Please add hacktoberAccepted Label too before merging
Thank You
=> Java Swing GUI Swap Two Numbers Program

flappywordgame.py
i create a flappy word game in python language
=> flappy word game

Python/stack_SDE.py
Want to add stack implementation code like stack implementation using array, linkedlist etc in python
=> stack imp. question pattern solution in python

fest2022/Find Longest Awesome Substring.txt, fest2022/Longest Happy Prefix.txt, fest2022/Minimum Insertion Steps to Make a String Palindrome.txt, fest2022/Number of Wonderful Substrings.txt, fest2022/Remove Invalid Parentheses.txt, fest2022/isomorphic strings.txt, fest2022/maximum sliding window.txt
I have added important hard string problem in dynamic programming which I got in my Microsoft , DE Shaw and Amazon interview . These are very important and frequently sked problem asked in core company . So please accept it.
=> Adding string problem in java

Number of Leaf Nodes
Count the number of leaf nodes in a binary tree
=> Create Number of Leaf Nodes

Minimum and Maximum in the Binary Tree
For a given a Binary Tree of type integer, find and return the minimum and the maximum data values. Return the output as an object of Pair class, which is already created
=> Create Minimum and Maximum in the Binary Tree

rock_paper_scissors.c
i have added a code for rock paper scissor in c
=> added a c code for rock paper scissor

C++/primeTill-n.cpp
print all prime number till n using seive algo in O(nlogn)
=>  program to print all prime till n in O(nlogn)

C++/matrix_multiplication.cpp
Added a C++ program to calculate matrix multiplication.
=> Added matrix multiplication program

C/Array_traversal.c
added and made it a bit more informative
=> changed a bit

Python/Count letters in String.py
=> I have added A python file named Count letters in straing in PYTHON folder

PatternPrograms
wrote a python program which includes 10 different types of pattern programs code written in oop.
=> Pattern programs

Python/keylogger.py
adding a basic keylogger for hacktoberfest 😄
=> add basic keylogger for hacktoberfest

C++/Dijkstra_Algo.cpp, C/Dijkstra_Algo.c, JavaScript/Dijkstra_Algo.js, Python/Dijkstra_Algo.py
Dear @Sirajmolla, 
I have added Dijkstra Algorithm in C++ , C , Python and JavaScript. 
Kindly review my PR and merge it ! 
Thanks a lot !
=> Added Dijkstra Algorithm Implementation in C++/C/Python/JS
